### ISSUE TITLE
Get a certificate for the Jenkins server.

### ISSUE THREAD

**Issue by ATMmachin3** [SugarcaneMC/sugarcanemc.org#1]
I'm not to sure where this belongs, but I noticed that the Jenkins server (ci.sugarcanemc.org) does not have a https certificate.

**Comment by Toffikk** [comment]
it has an https certificate

**Comment by ChrisChrome** [comment]
Arcane (for some reason) refuses to automatically forward http requests to https
visit the HTTPS version, it works

**Comment by TheArcaneBrony** [comment]
done
